### ISSUE TITLE
Align on CHANGELOG.md

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-app-ssot#123]
### Environment
* Nautobot version:  latest
* nautobot-ssot version: latest

We should use `CHANGELOG.md` at the repo root instead of keeping the change log in the docs. Then we can pull in that markdown file into the docs.

**Comment by chadell** [comment]
is this what we are implementing in the new standards? I thought towncrier is taking care of this for us...

**Comment by jdrew82** [comment]
This has been addressed with towncrier per internal discussion. Closing.
