### ISSUE TITLE
Pydantic 2.0 Migration

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-app-ssot#147]
As part of the pydantic 2.0 release, a suite of breaking changes were released. We need to investigate where this breaks diffsync.

Related:
- https://github.com/networktocode/diffsync/issues/236
- https://github.com/networktocode/circuit-maintenance-parser is also using pydantic, these should be upgraded in sync

**Comment by Kircheneer** [comment]
https://github.com/pydantic/bump-pydantic

**Comment by jdrew82** [comment]
This has been completed. Closing!
