### ISSUE TITLE
Stacked Device Support

### ISSUE THREAD

**Issue by ghost** [nautobot/nautobot-app-ssot#190]
### Environment

* nautobot version: 1.5.x
* nautobot-ssot-ipfabric version:  2.0.0
* ipfabric version: 6.x

#### IP Fabric

When IP Fabric discovers a stacked switch it creates a single record in the "Device Inventory" table.

Information about stacks can be found at the following tables:
- Switch stacks
  - This table contains a summary of stacked switches
  - 1 to 1 relationship with Device Inventory
  - API: `/api/v#.#/tables/platforms/stack`
  - UI: `/technology/platforms/stack/stacks`
- Stack Members
  - This table contains the individual members of the stack.
  - Many to 1 relationship with Device Inventory
  - API: `/api/v#.#/tables/platforms/stack/members`
  - UI: `/technology/platforms/stack/members`

Please see https://matrix.ipfabric.io/ (search `Stacking`) for which vendor and families IP Fabric supports stacked switches.
We are continually adding support for new vendors so please make sure to select the correct IPF version on the website.

#### Using Inventory > Part Numbers

See nautobot/nautobot-plugin-ssot#196

![image](https://user-images.githubusercontent.com/92743314/229892437-a06c3a4e-5116-4232-aecd-17439b5681f6.png)

#### Using Device Bay

- Query "Switch stacks" table (`/api/v#.#/tables/platforms/stack`).
- Sync "Device Inventory" table (`/api/v#.#/tables/inventory/devices`) to Nautobot.
  - Devices that have a `sn` in a switch stack must have a device type with Parent Status
- Query "Switch Member" table (`/api/v#.#/tables/platforms/stack/members`).
- Create a device for each member with a device type of Child Status
  - Device name `hostname-member` i.e `HWLAB-C3750-STACK-1`
- Parent device:
  - Add Device Bay with name "member" i.e. `1`
  - Add Child Device to Bay

Nautobot Breadcrumb:
- `Devices / LAB / HOSTNAME / BAY_NAME / INSTALLED_DEVICE`
- `Devices / LAB / HWLAB-C3750-STACK / 1 / HWLAB-C3750-STACK-1`

IP Fabric Cisco Example:

```json
[
  {
    "master": "HWLAB-C3750-STACK",
    "sn": "c0a86903",
    "siteName": "HWLAB",
    "connectionsCount": 2,
    "member": "1",
    "pn": "WS-C3750E-24TD-S",
    "memberSn": "FDO1607Y2W8",
    "role": "master",
    "state": "ready",
    "mac": "3cce.73a8.6e80",
    "ver": "12.2(55)SE12",
    "image": "C3750E-UNIVERSALK9-M",
    "hwVer": "1"
  },
  {
    "master": "HWLAB-C3750-STACK",
    "sn": "c0a86903",
    "siteName": "HWLAB",
    "connectionsCount": 2,
    "member": "2",
    "pn": "WS-C3750-24PS-S",
    "memberSn": "CAT0922K1HF",
    "role": "member",
    "state": "ready",
    "mac": "0014.6a06.2180",
    "ver": "12.2(55)SE12",
    "image": "C3750-IPSERVICESK9-M",
    "hwVer": "0"
  },
  {
    "master": "HWLAB-C3750-STACK",
    "sn": "c0a86903",
    "siteName": "HWLAB",
    "connectionsCount": 0,
    "member": "3",
    "pn": null,
    "memberSn": null,
    "role": "member",
    "state": "provisioned",
    "mac": "0000.0000.0000",
    "ver": null,
    "image": null,
    "hwVer": "0"
  }
]
```

![image](https://user-images.githubusercontent.com/92743314/229892596-8e4d1f6d-2e8e-46d8-82ec-a07815a684e1.png)

#### Using Inventory > Part Numbers

See nautobot/nautobot-plugin-ssot#196

#### Device Bays

- How do we define the Nautobot Device Type?
  - Generic model? `vendor-parent` and `vendor-child`?
- Will this work for all vendors?  I only have a Cisco example.
- Should we create a new `Device Role` for stack members?

#### Using Inventory > Part Numbers

- Pros:
  - Simpler and allows sync'ing all inventory parts
- Cons:
  - Limited information we can sync:
    - Part ID
    - Serial Number
    - Description

#### Device Bays

- Pros:
  - Can sync more information like image, version, etc.
- Cons:
  - Will it work for all vendors?
  - Lots of complexity and creating new devices, bays, and associating objects.

### Use Case

Collect important inventory information on stacked members like Part Numbers and Serial Information.

**Comment by jdrew82** [comment]
If these are truly stacked devices, ie devices where there's a single management/control plane and member devices that act as a cohesive unit, then I think using VirtualChassis for this makes much more sense than Device Bays. This is how we currently suggest representing Stackwise type devices from Cisco in Nautobot. This allows for you to have a Device per "blade" or member device (switch), and a Device to represent the control plane as the "master" device. Then each member device will have the relevant information on it, such as Interfaces, serial, etc and the master device will automatically show all Interfaces from member devices combined.
