### ISSUE TITLE
Use full names on interfaces with ipfabric

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot-app-ssot#307]
### Environment
* Nautobot version:  2.0.0
* nautobot-ssot version:  latest

### Proposed Functionality

Use full names on interfaces with ipfabric

Here:
https://github.com/nautobot/nautobot-plugin-ssot/blob/2a0f24d0612cbe934629d666a4ef9113cfa9e71b/nautobot_ssot/integrations/ipfabric/diffsync/adapter_nautobot.py#L96C11-L96C11

```python
                from netutils.interface import canonical_interface_name
                name=canonical_interface_name(interface_record.name),
```

### Use Case

Names correct to match configuration

**Comment by Kircheneer** [comment]
Seems like a breaking change to me. This raises the interesting question of whether all breaking changes in integrations warrant a major release, I would say so personally.

**Comment by jdrew82** [comment]
> Seems like a breaking change to me. This raises the interesting question of whether all breaking changes in integrations warrant a major release, I would say so personally.

If we're following SemVer technically breaking changes should absolutely warrant a major release.
