### ISSUE TITLE
Add common TypedDicts used for M2M into contrib.py

### ISSUE THREAD

**Issue by qduk** [nautobot/nautobot-app-ssot#310]
### Environment
* Nautobot version:  1.6.4
* nautobot-ssot version:  1.6.0

### Proposed Functionality
Add common typeddict's that would be commonly used for many-to-many relationships to a a new file (or contrib.py) so that they can be imported and used without the end developer having to define them. 

Some example TypedDicts we could include:

```python
class TagDict(TypedDict):
    """Many-to-many relationship typed dict explaining which fields are interesting."""

    name: str

class IPAddressDict(TypedDict):
    """Many-to-many relationship typed dict explaining which fields are interesting."""

    host: str
    prefix_length: int

class ContentTypeDict(TypedDict):
    """Many-to-many relationship typed dict explaining which fields are interesting.
    Needed for content_types:
    """

    app_label: str
    model: str
```

### Use Case
If I am creating an SSoT and need to use Tags or ContentTypes, I would typically have to define the TypedDict myself. Implementing this would allow us to import commonly used ones for ease of use.

**Comment by Renrut5** [comment]
@jdrew82 I would suggest this include TypedDicts not just for commonly used M2M objects, but all main Nautobot objects. This way the TypedDicts are already made and reusable in instances like custom relationships.

Thoughts?

**Comment by jdrew82** [comment]
This is something that @Kircheneer and I have discussed and I think we agree that it makes sense to have the common ones as an easily importable class in the framework so people don't have to recreate them all individually.
