### ISSUE TITLE
ACI Data Source job result error: ValidationError: ['"Site" is not a valid UUID.']

### ISSUE THREAD

**Issue by severance26** [nautobot/nautobot-app-ssot#338]
### Environment
* Python version: 3.8.17
* Nautobot version:  2.0.6
* nautobot-ssot version:  2.2.0

Run the Data Source job

Dryrun worked, but real run produced below error:
![image](https://github.com/nautobot/nautobot-app-ssot/assets/99373803/842a2c64-f396-41f5-a077-af635cc6be7d)

**Comment by jdrew82** [comment]
This should be fixed now by #339 so closing out.
