### ISSUE TITLE
1tm and MtM custom relationship syncs unable to handle foreign lookups in dictionaries

### ISSUE THREAD

**Issue by Renrut5** [nautobot/nautobot-app-ssot#340]
### Environment
* Python version:  3.8
* Nautobot version:  2.0.5
* nautobot-ssot version:  2.2.0

### Expected Behavior
Custom relationships to be created for many to many and one to many relationships.

### Observed Behavior
AttributeError when attempting to pull attribute from `related_object`.

### Steps to Reproduce
1. Custom relationships using TypedDict inputs in SSoT containing foreign lookups

**Comment by Renrut5** [comment]
I have a working fix that I will create a PR for shortly.

**Comment by Kircheneer** [comment]
Thanks for the issue! Are you working on this still?

**Comment by Kircheneer** [comment]
Should be fixed with either 2.5.0 or 1.6.3, please try.
