### ISSUE TITLE
Custom 1-to-Many Relationships Error when defining Destination side

### ISSUE THREAD

**Issue by Renrut5** [nautobot/nautobot-app-ssot#352]
### Environment
* Python version:  3.8
* Nautobot version:  2.1.2
* nautobot-ssot version:  2.2.0

### Expected Behavior
SSoT to create custom one to many relationships when defining the relationship from the destination side.

### Observed Behavior
An error occurs as the returned value from `_handle_custom_relationship_to_many_relationship` method is always a list of objects regardless if it is 1-to-many or many-to-many.

When `RelationshipSideEnum.DESTINATION` is used on 1-to-many relationships, a single object is expected, not a list of objects.

### Steps to Reproduce
1. Define 1-to-many custom relationships in SSoT and build relationships from destination side

**Comment by Kircheneer** [comment]
Can you share some code how we can reproduce this?

**Comment by Kircheneer** [comment]
Is this the same as #392 ?

**Comment by chadell** [comment]
I have a fix, going to contribute it

**Comment by Renrut5** [comment]
@chadell @Kircheneer , is this considered completed from the merge for #393 ?

**Comment by Kircheneer** [comment]
IMO this can be closed, yes. Feel free to re-open in case you encounter any issues. Thanks!
