### ISSUE TITLE
Migrate Zero reversibility failures

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot-app-ssot#391]
### Environment
* Python version:  3.11
* Nautobot version:  2.1.x
* nautobot-ssot version:  latest

### Expected Behavior
nautobot-server migrate nautobot_ssot zero

### Observed Behavior

Failed for RunPython missing reverse_code
* 0006

### Steps to Reproduce
1.
2.
3.

**Comment by gsnider2195** [comment]
Fixed in #567
