### ISSUE TITLE
The external integration in the demo job should be optional

### ISSUE THREAD

**Issue by ubajze** [nautobot/nautobot-app-ssot#462]
### Environment
* Python version:  3.11.9
* Nautobot version:  2.2.4
* nautobot-ssot version:  2.6.0

### Expected Behavior
I expect to either select an external integration or source URL/token in the demo job.

### Observed Behavior
All fields (external integration, source URL and source token) are mandatory in the demo job, which means that source URL/token are never used based on this code: https://github.com/nautobot/nautobot-app-ssot/blob/930d61e5b81b49d0571364be3a17ef702901b75a/nautobot_ssot/jobs/examples.py#L653-L663

### Steps to Reproduce
1. Enable demo jobs
2. Run the demo job

**Comment by jdrew82** [comment]
@ubajze I believe this has been resolved. I've tested it with the 3.0.0 release and can confirm that the ExternalIntegration isn't required for the DataSource Job to work.
