### ISSUE TITLE
SSOT Installation Issue - Nautobot Server Post Upgrade Issue 

### ISSUE THREAD

**Issue by ShivaniMauryaIntel** [nautobot/nautobot-app-ssot#465]
### Environment
* Python version:  3.8.0
* Nautobot version:  2.1.8

nautobot server post upgrade completed

Getting below error -
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

### Steps to Reproduce
1. Install nautobot using docker
2. Run the command - "nautobot-server post_upgrade" which fails

**Comment by ShivaniMauryaIntel** [comment]
I have followed this video to install Nautobot in Lab - https://www.youtube.com/watch?v=X6g-5iwr9hI
Now, I am following this document to install SSOT for ACI integration, but failing at post-upgrade command -
https://docs.nautobot.com/projects/ssot/en/latest/admin/install/#install-guide

**Comment by Kircheneer** [comment]
Can you share your `nautobot_config.py` file?

**Comment by ShivaniMauryaIntel** [comment]
Hi,

I have re-installed nautobot from scratch, & the post upgrade command is working.
However, I am not seeing any Data Sources after installing ACI SSOT –

***@***.***

I have used the below command to install ACI SSOT –

pip install nautobot-ssot[aci]

Regards,
Shivani Maurya

**Comment by ShivaniMauryaIntel** [comment]
PFA the nautobot_config.py.


Regards,
Shivani Maurya

From: Maurya, Shivani
Sent: Thursday, June 6, 2024 6:07 PM
To: nautobot/nautobot-app-ssot ***@***.***>; nautobot/nautobot-app-ssot ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [nautobot/nautobot-app-ssot] SSOT Installation Issue - Nautobot Server Post Upgrade Issue (Issue #465)

Hi,

I have re-installed nautobot from scratch, & the post upgrade command is working.
However, I am not seeing any Data Sources after installing ACI SSOT –

***@***.***

I have used the below command to install ACI SSOT –

pip install nautobot-ssot[aci]

Regards,
Shivani Maurya

**Comment by ShivaniMauryaIntel** [comment]
It is resolved by adding env variables in path file. - https://josh-v.com/nautobot-environment-file/
