### ISSUE TITLE
aci_apics is list-type in default_settings, but dictionary in PLUGINS_CONFIG

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot-app-ssot#474]
### Environment
* Python version:  3.11
* Nautobot version: v2.2.6
* nautobot-ssot version:  v2.6.1

### Impact
There is no impact to SSoT App itself from this

### Expected Behavior
Both objects are the same type of object in template vs runtime for consistency
I think it may be intended to be an empty dictionary here?

### Observed Behavior
The [aci_apics](https://github.com/nautobot/nautobot-app-ssot/blob/a9beea04a7d905d180d08d17ed3876b8f3871edc/nautobot_ssot/__init__.py#L52) object in the App Config default_settings is an empty list
```python
default_settings = {
    "aci_apics": [],
```

In the [PLUGINS_CONFIG](https://github.com/nautobot/nautobot-app-ssot/blob/b4f10348144b4626482de2b334d73085f6f66be1/development/nautobot_config.py#L149) for aci_apics the resulting object would be a dictionary
```python
PLUGINS_CONFIG = {
    "nautobot_ssot": {
        "aci_apics": {x: os.environ[x] for x in os.environ if "APIC" in x},
```

### Steps to Reproduce
1. None

### Notes
The SSoT App itself is not directly affected
The difference seems to be an issue for consumers who create a definition with a type-based constraint from the default_settings (list) vs consuming in regards to PLUGINS_CONFIG (dictionary)

**Comment by jdrew82** [comment]
I'm going to close this out as the ACI integration has been updated to use Controllers.
