### ISSUE TITLE
Infoblox Installation Missing Enable

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-ssot#520]
### Environment
* Python version:  3.8+
* Nautobot version:  2.3.0
* nautobot-ssot version:  3.0.0

### Expected Behavior
Expected to see full instructions on installing and setting up Infoblox integration.

### Observed Behavior
Found the documentation missing a note about setting `enable_infoblox` to True in PLUGINS_CONFIG for `nautobot_ssot`. It appears this was accidentally removed during the documentation revamp when the settings were moved to a config object.

### Steps to Reproduce
1. Review Infoblox integration installation instructions.
2. Attempt to follow and find Infoblox integration is not enabled.
3.

**Comment by Kircheneer** [comment]
Closed by #529
