### ISSUE TITLE
Determine Reasoning for Exception Handling in Example Job

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-ssot#521]
### Environment
* Python version:  3.8
* Nautobot version:  2.3.0
* nautobot-ssot version:  3.0.0

It appears that there's a try/except block capturing all Exceptions in the DataSource Job [here](https://github.com/nautobot/nautobot-app-ssot/blob/8d007faba8dabeda4a23aaa9c210e6485b870149/nautobot_ssot/jobs/examples.py#L871). We need to investigate to see why this is and most likely remove and change to only capture expected Exceptions and allow others to populate.

**Comment by Kircheneer** [comment]
Looks like it should be `nautobot.extras.exceptions.SecretError`
