### ISSUE TITLE
Unable to view Infoblox Configuration List

### ISSUE THREAD

**Issue by nopg** [nautobot/nautobot-app-ssot#530]
### Environment
* Python version: 3.11.9
* Nautobot version:  2.3.1
* nautobot-ssot version:  3.0.1

### Expected Behavior
To be presented with a page listing any existing Infoblox Configurations, and ability to create a new Configuration.

### Observed Behavior
Traceback with: `'NoneType' object has no attribute '__name__'`
`Exception Location: | /usr/local/lib/python3.11/site-packages/nautobot/core/templatetags/helpers.py, line 798, in saved_view_modal`

### Steps to Reproduce
1. From the home page, choose Apps -> Installed Apps
2. Click the orange cog (configure) for Single Source of Truth
3. Click "Infoblox Configuration List"

### Cause/Fix
This is caused by Saved Views being implemented in Nautobot 2.3+. At [/nautobot/core/templates/generic/object_list.html , line 263](https://github.com/nautobot/nautobot/blob/15c8b869bb76eb806e4a5a44302bcc06cebf5679/nautobot/core/templates/generic/object_list.html#L263) it determines that the SSOTInfobloxConfig model is a saved view (new default setting). This model has no need for ever being a saved view.

The fix will be to set `is_saved_view_model = False` for the `class SSOTInfobloxConfig`, PR incoming.

**Comment by alhogan** [comment]
Can this be back ported to the 2.8 LTM as well?
