### ISSUE TITLE
ACI Job Fails with Controller Managed Device Group Error

### ISSUE THREAD

**Issue by ShivaniMauryaIntel** [nautobot/nautobot-app-ssot#551]
### Environment
* Python version:  3.9.18
* Nautobot version:  2.3.2
* nautobot-ssot version:  3.1.0

ACI Job Successful

ACI Job Failed with error - "Controller Managed Device group" 
![image](https://github.com/user-attachments/assets/8496dd08-fd8a-4a16-bb7d-efde6dff3815)

### Steps to Reproduce
1. Uninstall & Install the latest version of ssot[aci] code which is fixed as part of the bug - https://github.com/nautobot/nautobot-app-ssot/issues/479
2. Run the ACI Sync Job Again
3. The job fails with the error of "Controller Managed device group"
4. Check on the nautobot server if the latest code is being pulled. You will still see that the old code is pulled instead of the new code -
![image](https://github.com/user-attachments/assets/944f3a4e-d676-4924-a0d7-4dbcefac99b9)

Please check if the main branch has this code change.

**Comment by ShivaniMauryaIntel** [comment]
Also, the code changes are not updated on Github repo for the v3.1.0 -
![image](https://github.com/user-attachments/assets/5ca2d92f-cfa4-46d2-9ffa-8b6cb46536dc)

**Comment by jdrew82** [comment]
This was fixed in #547.
