### ISSUE TITLE
PluginTemplateExtension Deprecated

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-ssot#598]
### Environment
* Python version:  3.11
* Nautobot version:  2.3.11
* nautobot-ssot version:  3.2.0

### Expected Behavior
Expect no warning.

### Observed Behavior
Received warning when running tests:

`21:57:59.987 WARNING nautobot.core.utils.deprecation template_content.py                       <module>() : Class PluginTemplateExtension is deprecated, and will be removed in a future Nautobot release. Instead of deriving JobResultSyncLink from PluginTemplateExtension, please migrate your code to inherit from class TemplateExtension instead.`

### Steps to Reproduce
1. Run tests for SSoT and review logs.
2.
3.

**Comment by Kircheneer** [comment]
Closed in [dfe4a2e](https://github.com/nautobot/nautobot-app-ssot/commit/dfe4a2ed14eecf60c76f71b106cf47c38f211511) - note that there is no MR because I accidentally pushed directly to `develop`, it has since then been protected.
