### ISSUE TITLE
Add Slurpit Support

### ISSUE THREAD

**Issue by lpconsulting321** [nautobot/nautobot-app-ssot#600]
### Environment
* Nautobot version:  v2+
* nautobot-ssot version: v3.2.0+

### Proposed Functionality
Add the ability to sync data from network discovery using slurpit.io. Ability to sync device, sites, IP's and more. 

### Use Case
Slurpit users would like an easy way to be able to sync data discovered from Slurpit into Nautobot to further develop their source of truth.

**Comment by chadell** [comment]
Isn't https://slurpit.io/nautobot-plugin/ working well for you?

**Comment by jdrew82** [comment]
@lpconsulting321 Isn't this already covered by the App that Slurpit made? https://slurpit.io/nautobot-plugin/

**Comment by pietos** [comment]
We worked on this ssot app implementation since we got a couple requests for it. It's more flexible for other data models then the once that are in the plugin for the moment.

**Comment by lpconsulting321** [comment]
Closing ticket as this has been merged.
