### ISSUE TITLE
Create Reusable Nautobot Models

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-ssot#63]
### Environment
* Nautobot version:  1.4.5
* nautobot-ssot version:  1.2.0

### Proposed Functionality
It would be useful to have defined models for the Nautobot SoR that can be reused across SSoT plugins.

### Use Case
During the course of building an SSoT plugin there is a lot of replicated code on the Nautobot side as the models and CRUD operations don't change. It'd be helpful if we had defined models that cover all attributes of importable Nautobot models and the appropriate CRUD methods for each and allow the plugin developer to define the objects to import and attributes to match on.

**Comment by Kircheneer** [comment]
@itdependsnetworks is working on something that should address this

**Comment by chadell** [comment]
> @itdependsnetworks is working on something that should address this

I think that the approach from @itdependsnetworks helps on that line, but what this FR is about is adding support for "all" Nautobot models, with their diffsync version (plus the adapters).

**Comment by itdependsnetworks** [comment]
I agree, that being said, I think we should hold off looking to make any more progress until this initial feature set is added. I think while technically feasible, I am not sure the complication will make it "worth it", and would like to pause after this section.

**Comment by itdependsnetworks** [comment]
No tests or anything and in draft, but some rough idea where this is going #69

**Comment by Kircheneer** [comment]
#153 too

**Comment by Kircheneer** [comment]
I would say at this point most of the original issues were addressed through `nautobot_ssot.contrib` so I'm closing this one out.
